node {
  stage('Build Image') {

    git credentialsId: 'bc4cdd02-8691-46c4-bb93-20278a920677', url: 'git@bitbucket.org:devservices/pinones.git'

    dir("webfrontend") {
      docker.build("node-frontend")
      stage("Test") {
        sh "docker run node-frontend npm test"
      }
      stage("Lint") {
        sh "docker run node-frontend npm run lint"
      }
      stage("Build") {
        sh "docker run node-frontend /bin/bash -c 'npm run build; aws s3 cp /usr/src/app/build s3://pinones --recursive'"
      }
    }
  }
}
