---

  - name: Create target directories
    file:
      path: "/tmp/{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - common-utils/src/common_utils
      - front-end/resources/public/css
      - front-end/resources/views/templates
      - front-end/src/front_end
      - front-end/test/front_end/integration
      - front-end/test/front_end/unit
      - newsfeed/resources
      - newsfeed/src/newsfeed
      - newsfeed/test/newsfeed/integration
      - newsfeed/test/newsfeed/unit
      - newsfeed/test/resources
      - quotes/resources
      - quotes/src/quotes
      - quotes/test/quotes/integration


  - name: Copy in common-utils
    copy:
      src: "../../../{{ item }}"
      dest: "/tmp/{{ item }}"
      # directory_mode: True
      mode: 0755
      owner: ec2-user
      group: ec2-user
      force: yes
    with_items:
      - common-utils/src/common_utils/core.clj
      - common-utils/src/common_utils/middleware.clj
      - common-utils/test/common_utils/middleware_test.clj
      - common-utils/Dockerfile
      - common-utils/Makefile
      - common-utils/pom.xml
      - common-utils/project.clj
      - front-end/resources/public/css/bootstrap.min.css
      - front-end/resources/public/serve.py
      - front-end/resources/views/templates/base.html
      - front-end/resources/views/templates/home.html
      - front-end/resources/logback.xml
      - front-end/src/front_end/core.clj
      - front-end/src/front_end/data.clj
      - front-end/src/front_end/utils.clj
      - front-end/src/front_end/views.clj
      - front-end/test/front_end/integration/core.clj
      - front-end/test/front_end/unit/data.clj
      - front-end/Dockerfile
      - front-end/Makefile
      - front-end/project.clj
      - newsfeed/resources/logback.xml
      - newsfeed/src/newsfeed/api.clj
      - newsfeed/src/newsfeed/core.clj
      - newsfeed/test/newsfeed/integration/api.clj
      - newsfeed/test/newsfeed/unit/api.clj
      - newsfeed/test/resources/logback-test.xml
      - newsfeed/Dockerfile
      - newsfeed/Makefile
      - newsfeed/pom.xml
      - newsfeed/project.clj
      - quotes/resources/logback.xml
      - quotes/resources/quotes.json
      - quotes/src/quotes/api.clj
      - quotes/src/quotes/routes.clj
      - quotes/test/quotes/integration/api.clj
      - quotes/Dockerfile
      - quotes/Makefile
      - quotes/project.clj


  - name: Copy in docker compose
    copy:
      src: "../../../../docker-compose.yml"
      dest: "/tmp/docker-compose.yml"
      mode: 0755
      owner: ec2-user
      group: ec2-user
      force: yes

  - name: install Docker compose
    shell: curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.15.0/docker-compose-$(uname -s)-$(uname -m)"
    ignore_errors: true

  - name: wait for install
    wait_for:
      timeout: 10

  - name: change permissions Docker compose
    file:
      path: /usr/local/bin/docker-compose
      mode: 0755


  - name: build base image
    shell: docker build -f /tmp/common-utils/Dockerfile -t infrabase /tmp/common-utils

  - name: Remove old containers
    shell: /usr/local/bin/docker-compose rm -f
    args:
      chdir: /tmp/
    ignore_errors: true

  - name: Pull new config for docker compose
    shell: /usr/local/bin/docker-compose pull
    args:
      chdir: /tmp/

  - name: Build containers and demonise
    shell: /usr/local/bin/docker-compose up --build -d
    args:
      chdir: /tmp/
