node {
  stage('Build Image') {

    git credentialsId: 'bc4cdd02-8691-46c4-bb93-20278a920677', url: 'git@bitbucket.org:devservices/pinones.git'
    sh "chmod 600 /var/jenkins_home/.ssh/id_rsa"
    sh "ssh-agent bash -c 'ssh-add /var/jenkins_home/.ssh/id_rsa'"

    dir("containers/${APPLICATION}") {
      hash = "${HASH}".trim()
      app = docker.build("878039544970.dkr.ecr.eu-west-2.amazonaws.com/spike/${APPLICATION}:${hash}")
    }
  }

  stage('AWS Login') {
    sh """aws ecr get-login --region eu-west-2 > login.txt"""
    sh """cut -d' ' -f1-6,9- login.txt | sh"""
    // sh """aws ecr describe-repositories --region eu-west-2 --query 'repositories[*].repositoryName' > /tmp/repoNames.txt"""
    //
    // if (readFile('/tmp/repoNames.txt').contains("/${APPLICATION}")) {
    //   sh """aws ecr create-repository --region eu-west-2 --repository-name spike/${APPLICATION}"""
    // }

  }
  stage('Push Image') {
    sh """docker push 878039544970.dkr.ecr.eu-west-2.amazonaws.com/spike/${APPLICATION}:${hash}"""
  }
}
